# Generated by Django 4.1 on 2024-03-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
