# Generated by Django 4.1 on 2024-04-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
