# Generated by Django 4.1 on 2024-04-04 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_course_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_readiness_score", models.FloatField()),
                ("areas_of_struggle", models.JSONField(default=dict)),
                ("estimated_lexile_level", models.IntegerField()),
                ("confidence_score", models.FloatField()),
                ("reading_speed", models.FloatField()),
                ("previous_lexile_levels", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="PracticeSessions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("strategy", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpenQuestions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("question", models.TextField()),
                ("response", models.TextField()),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("pink_highlights", models.JSONField(default=list)),
                ("yellow_highlights", models.JSONField(default=list)),
                ("notes", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCQuestions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("question", models.TextField()),
                ("response", models.TextField()),
                ("answer", models.TextField()),
                ("correct", models.BooleanField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="metrics",
            field=models.ManyToManyField(blank=True, to="pages.metrics"),
        ),
    ]
