# Generated by Django 4.1 on 2024-04-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_metrics_practicesessions_openquestions_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="metrics",
        ),
        migrations.AddField(
            model_name="customuser",
            name="metrics",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.metrics",
            ),
        ),
    ]
