# Generated by Django 4.1 on 2024-04-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_alter_course_id_alter_course_teacher_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="notes",
            name="reading",
            field=models.TextField(null=True),
        ),
    ]
