# Generated by Django 4.1 on 2024-04-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_alter_practicesessions_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicesessions",
            name="strategy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.strategy",
            ),
        ),
    ]
