# Generated by Django 4.1 on 2024-04-04 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_alter_practicesessions_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
