# Generated by Django 5.0.3 on 2024-04-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='quiz_scores',
            field=models.JSONField(default=dict),
        ),
    ]
