# Generated by Django 5.0.3 on 2024-04-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_metrics_quiz_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='quiz_scores',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='test_readiness_score',
            field=models.FloatField(null=True),
        ),
    ]
