# Generated by Django 5.0.3 on 2024-04-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_metrics_quiz_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='areas_of_struggle',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
