# Generated by Django 5.0.3 on 2024-04-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_metrics_areas_of_struggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestions',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='openquestions',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='practicesessions',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
