# Generated by Django 5.0.3 on 2024-04-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_mcquestions_date_alter_notes_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='estimated_cefr_rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='estimated_level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
