# Generated by Django 5.0.3 on 2024-04-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_metrics_estimated_cefr_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='confidence_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='estimated_lexile_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='previous_lexile_levels',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='reading_speed',
            field=models.FloatField(null=True),
        ),
    ]
