# Generated by Django 5.0.3 on 2024-04-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_metrics_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='diagnostic',
            field=models.BooleanField(default=False),
        ),
    ]
