# Generated by Django 5.0.3 on 2024-04-10 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_customuser_diagnostic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='mcquestions',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mcquestions',
            name='student',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='previous_lexile_levels',
        ),
        migrations.RemoveField(
            model_name='metrics',
            name='quiz_scores',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='student',
        ),
        migrations.RemoveField(
            model_name='openquestions',
            name='course',
        ),
        migrations.RemoveField(
            model_name='openquestions',
            name='student',
        ),
        migrations.RemoveField(
            model_name='practicesessions',
            name='strategy',
        ),
        migrations.AddField(
            model_name='metrics',
            name='average_length_of_highlight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='average_questions_asked',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='average_questions_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='average_reading_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='average_removed_highlights',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='average_uknown_words',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='cause_effect',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='pages.course'),
        ),
        migrations.AddField(
            model_name='metrics',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='descriptive',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='explicit_details',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='implicit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='location_details',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='poetry_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='problem_solution_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='quiz_score_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='sequences',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='story_elements_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openquestions',
            name='grade',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='practice_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='pages.practicesessions'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='openquestions',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='openquestions',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('removed_highlights', models.IntegerField(null=True)),
                ('number_of_highlights', models.IntegerField(null=True)),
                ('number_of_unknown_words', models.IntegerField(null=True)),
                ('avg_length_of_highlight', models.FloatField(null=True)),
                ('is_reading', models.BooleanField(null=True)),
                ('estimated_lexile_level_text', models.IntegerField(null=True)),
                ('time_seconds', models.FloatField(null=True)),
                ('left_page', models.IntegerField(null=True)),
                ('order_answers', models.CharField(max_length=200, null=True)),
                ('missing_answers', models.IntegerField(null=True)),
                ('right_answers', models.IntegerField(null=True)),
                ('total_questions', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='pages.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mcquestions',
            name='raw_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mc_questions', to='pages.rawdata'),
        ),
        migrations.AddField(
            model_name='metrics',
            name='raw_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='pages.rawdata'),
        ),
        migrations.AddField(
            model_name='notes',
            name='raw_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pages.rawdata'),
        ),
        migrations.AddField(
            model_name='openquestions',
            name='raw_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='pages.rawdata'),
        ),
        migrations.AddField(
            model_name='practicesessions',
            name='raw_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='pages.rawdata'),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('lexile_level', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='pages.rawdata')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTeacherQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('answered', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher_questions', to='pages.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_teacher_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
