# Generated by Django 5.0.3 on 2024-04-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_customuser_metrics_remove_mcquestions_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='practice_session',
        ),
        migrations.AddField(
            model_name='strategy',
            name='practice_session',
            field=models.ManyToManyField(blank=True, null=True, related_name='strategies', to='pages.practicesessions'),
        ),
    ]
