# Generated by Django 5.0.3 on 2024-04-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_strategy_practice_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='practice_session',
            field=models.ManyToManyField(blank=True, related_name='strategies', to='pages.practicesessions'),
        ),
    ]
