# Generated by Django 5.0.3 on 2024-04-12 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_strategy_practice_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesessions',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='pages.practicesessions'),
        ),
    ]
