# Generated by Django 5.0.3 on 2024-04-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_practicesessions_raw_data_rawdata_raw_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdata',
            old_name='raw_data',
            new_name='practice_session',
        ),
    ]
