# Generated by Django 5.0.3 on 2024-04-12 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_rename_raw_data_rawdata_practice_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='raw_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='pages.rawdata'),
        ),
    ]
