# Generated by Django 5.0.3 on 2024-04-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_reading_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='is_reading',
        ),
    ]
