# Generated by Django 5.0.3 on 2024-04-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_rawdata_is_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
