# Generated by Django 4.2.13 on 2024-05-12 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0027_alter_rawdata_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenWriting",
            fields=[
                (
                    "qid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
