# Generated by Django 4.2.13 on 2024-05-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0028_openwriting"),
    ]

    operations = [
        migrations.AddField(
            model_name="openwriting",
            name="id_user",
            field=models.IntegerField(null=True),
        ),
    ]
