# Generated by Django 4.2.13 on 2024-05-12 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0029_openwriting_id_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpenWriting",
        ),
    ]
