# Generated by Django 4.2.13 on 2024-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0030_delete_openwriting"),
    ]

    operations = [
        migrations.CreateModel(
            name="WritingPrompts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="writing_prompts",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="pages.writingprompts"
            ),
        ),
    ]
