# Generated by Django 4.2.13 on 2024-06-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0031_writingprompts_course_writing_prompts"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
