# Generated by Django 4.2.13 on 2024-06-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0032_reading_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="color",
            field=models.CharField(default="#132143", max_length=100),
        ),
    ]
