# Generated by Django 4.2.13 on 2024-08-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0033_customuser_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(default="UTC", max_length=100),
        ),
    ]
