# Generated by Django 4.2.13 on 2024-08-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0036_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="review_date",
            field=models.DateTimeField(),
        ),
    ]
