# Generated by Django 4.2.13 on 2024-08-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0038_quizscore_binarysearchparameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binarysearchparameters",
            name="high",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="binarysearchparameters",
            name="low",
            field=models.IntegerField(null=True),
        ),
    ]
