# Generated by Django 4.2.13 on 2024-08-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0039_alter_binarysearchparameters_high_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
