# Generated by Django 4.2.13 on 2024-08-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0041_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="item_num",
            field=models.IntegerField(null=True),
        ),
    ]
