# Generated by Django 4.2.13 on 2024-08-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0042_alter_feedback_item_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="item_type",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
