# Generated by Django 4.2.13 on 2024-08-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0043_feedback_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="user_occupation",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
