# Generated by Django 4.2.13 on 2024-08-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0044_feedback_user_occupation"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tour",
            field=models.BooleanField(default=False),
        ),
    ]
